---
title: Comino Matas.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Blog de Comino Ilustración
description: Blog personal de Rafael Comino Matas sobre ilustración, dibujo y todo
  lo que se me ocurra...
avatar: https://cominoilustracion.com/images/milogo.svg
footer-links:
  dribbble: 
  email: cominomatas@gmail.com
  facebook: rafael.cominomatas
  flickr: RafaCM...
  github: 
  instagram: 
  linkedin: 
  pinterest: cominomatas
  rss: RCM
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: cominoilustracion
google_analytics: UA-89378942-1
url: https://blog.cominoilustracion.com
enforce_ssl: yoursite.com
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
excerpt_separator: "<!--more-->"
paginate: 6
paginate_path: "/page:num/"
